version: '3.4'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8081:8080
    networks:
      - app
      
networks:
  app: